.TH XCHAT\-TEXT 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
xchat \- irc client for X.
.SH SYNOPSIS
.B xchat
.SH "DESCRIPTION"

 Good looking GTK+ GUI 
 Looks and behaves alot like AmIRC (Amiga) 
 DCC SEND 
 DCC RECEIVE 
 DCC RESUME (mIRC extension) 
 mIRC Color 
 Multiple Server/Channel windows with 1 thread 
 Dialog Windows (like /query in BitchX) 
 Alot of other things, you'll have to try it! 

.SH "SEE ALSO"
.IR yagirc(1),
.IR bezerk(1), 
.IR ircII(1)
.SH AUTHOR
This manual page was written by David N. Welton <davidw@efn.org>,
for the Debian GNU/Linux system (but may be used by others).
