#
# Currently just a scratchpad for testing whatever happens to need it
#

import PGBuild.Config
env = Environment()

# Use the default configuration tree
conf = PGBuild.Config.default

# Mount the sources.xml from conf-dev read-only
# and our test.xml read-write
conf.mount(env.fs.Entry("../conf-dev/sources.xml"))
conf.mount(env.fs.Entry("test.xml"), "rw")

# Show the list of mounts
print conf.mounts

# Print the whole config tree
print conf.toprettyxml()

# Build a 'hello world'
#prog = env.Program('hello', 'hello.c')
#Default(prog)

# Add a dependency, so the hello world should be rebuilt
# when we change the <important/> part of the XML document,
# but not when we change other parts.
#env.Depends(prog, tag)

