#!/usr/bin/perl
#
# Little utility to convert a hex value to human readable divnode flags
#
# -- Micah Dowty <micahjd@users.sourceforge.net>
#

@d = qw(
	DIVNODE_NEED_RECALC
	DIVNODE_NEED_REDRAW
	DIVNODE_UNIT_PERCENT
	DIVNODE_SPLIT_TOP
	DIVNODE_SPLIT_BOTTOM
	DIVNODE_SPLIT_LEFT
	DIVNODE_SPLIT_RIGHT
	DIVNODE_SPLIT_BORDER
	DIVNODE_SPLIT_CENTER
	DIVNODE_NEED_REBUILD
	DIVNODE_SPLIT_IGNORE
	DIVNODE_SPLIT_EXPAND
	DIVNODE_PROPAGATE_REDRAW
	DIVNODE_SCROLL_ONLY
	DIVNODE_INCREMENTAL
	DIVNODE_UNIT_CNTFRACT
	DIVNODE_GROPLIST_DIRTY
	DIVNODE_SIZE_RECURSIVE
	DIVNODE_SIZE_AUTOSPLIT
	DIVNODE_SPLIT_POPUP
	DIVNODE_HOTSPOT
	DIVNODE_POPUP_NONTOOLBAR
	DIVNODE_NOSQUISH
	DIVNODE_EXTEND_WIDTH
	DIVNODE_EXTEND_HEIGHT
	DIVNODE_DIVSCROLL
	DIVNODE_PROPAGATE_SCROLL
	DIVNODE_AUTOWRAP
	DIVNODE_CONTINUATION_LINE
	DIVNODE_UNDERCONSTRUCTION
	DIVNODE_FORCE_CHILD_RECALC
	);

while(<>){@e=@d;$_=eval;while($_){print "\t".$e[0]."\n" if($_&1);shift @e;$_>>=1;}}

### The End ###
