BINNAME = mips-uspread
SRC     = uspread.c util.c

$(BINNAME): $(SRC)
	mipsel-linux-gcc -msoft-float -o $(BINNAME) $(SRC) -lpgui -g -I../../cli_c/include -L../../cli_c/src/.libs
	mipsel-linux-strip $(BINNAME)

clean:
	rm -f $(BINNAME) *.o

