Webalizer V1.30-05 (Linux 2.2.16-urw3) English
Using logfile /home/groups/webqcat/log/access_log
Creating output in /home/groups/webqcat/htdocs/webalizer
Hostname for reports is 'webqcat.sourceforge.net'
Reading history file... webalizer.hist
Generating report for September 2000
Generating report for October 2000
Generating report for November 2000
Generating summary report
Saving history information...
6508 records (1718 ignored) in 3.14 seconds, 2072/sec
