#!/bin/sh -e 

if [ ! -d debian/build/xchat-gnome/usr/share/pixmaps ]; then
        install -d -o root -g root -m 755 debian/build/xchat-gnome/usr/share/pixmaps
	install -p -o root -g root -m 644 *.png debian/build/xchat-gnome/usr/share/pixmaps
fi
