#define OWNEDBUTEMPTY GRIDGAME_USER
#define ONEQUARTER GRIDGAME_USER+1
#define TWOQUARTERS GRIDGAME_USER+2
#define THREEQUARTERS GRIDGAME_USER+3
#define FOURQUARTERS GRIDGAME_USER+4

PROPDECL(ownedbutempty,OWNEDBUTEMPTY)
PROPDECL(onequarter,ONEQUARTER)
PROPDECL(twoquarters,TWOQUARTERS)
PROPDECL(threequarters,THREEQUARTERS)
PROPDECL(fourquarters,FOURQUARTERS)
