#!/bin/sh

# Some links to help find everything
ln -s ../../pgserver/pgserver .
ln -s ../PicoGUI.pm .

# I'm probably going to replace this with an arg to the server to start a
# client... That way, the server can start the client immediately after
# the server is done initializing, and the server can quit as soon as the
# client exits.
#
./pgserver&
sleep 1
./typing.pl
killall pgserver

