#!/usr/bin/env python
#
# Simple CGI script to generate a page with per-project
# message counts generated by the CIA bot.
#

import os

statDir = "/home/commits/stats"
channelFile = "/home/commits/channels.list"

# List out the subdirs explicitly so we can set the order-
# the first one here is used as the sort key, and for definatively
# listing the available projects.
statSubdirs = ('forever', 'monthly', 'weekly', 'end-of-day', 'daily')

projects = os.listdir(os.path.join(statDir, statSubdirs[0]))
channels = open(channelFile).read().strip().split("\n")

projectCounts = {}
for project in projects:
    # Build a map of counts indexed by subdirectory
    counts = {}
    for subdir in statSubdirs:
        try:
            counts[subdir] = int(open(os.path.join(statDir, subdir, project)).read().strip())
        except IOError:
            counts[subdir] = 0
    projectCounts[project] = counts

# Sort the project list by the 'forever' count, descending
def countSort(a,b):
    return cmp(projectCounts[b][statSubdirs[0]],
               projectCounts[a][statSubdirs[0]])
projects.sort(countSort)

# Page heading
print """Content-type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <title>CIA bot statistics</title>
  <style type="text/css" media="all"> @import url(http://navi.picogui.org/svn/picogui/trunk/tools/css/cia_stats.css);
  </style>
</head>
<body>

<div class="heading">
   <div class="title">CIA bot statistics</div>
   <div class="subtitle">Because SF stats weren't pointless enough</div>
</div>

<div><span class="section">Number of messages posted per project</span></div>
<div class="section">
  <div class="sectionTop"></div>
  <div class="row">
    <table>
"""

# Project table heading
print "<tr>",
for heading in ('Project',) + statSubdirs:
    print '<th>%s</th>' % heading,
print "</tr>"

# Project table contents
for project in projects:
    print "<tr><td>%s</td>" % project,
    for subdir in statSubdirs:
        count = projectCounts[project][subdir]
        if count:
            print "<td>%s</td>" % count,
        else:
            print "<td></td>",
    print "</tr>"
    
print """

    </table>
  </div>
</div>

<div><span class="section">Channels the bot is currently in</span></div>
<div class="section">
  <div class="sectionTop"></div>
  <div class="row">
    <ul>
"""
for channel in channels:
    print "<li>%s</li>" % channel
print """
    </ul>
  </div>
</div>

</body>
</html>
"""
