#!/bin/sh
#
# Simple CGI script to generate a page with per-project
# message counts generated by the CIA bot.
#
STATDIR=/home/commits/stats
CHANNELFILE=/home/commits/channels.list

# Sure, let's use bash as an HTML templating language :-)
echo -ne "Content-type: text/html\n\n"
cat <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <title>CIA bot statistics</title>
</head>
<body>
<h1>CIA bot statistics</h1>

<p>Number of messages posted per project:</p>

<table border="1" cellspacing="0" cellpadding="5">
<tr><td> <b>Project</b> </td><td> <b>Messages</b> </td></tr>

EOF
(cd $STATDIR; for file in *; do
  echo "<tr><td>" $file "</td><td>" `cat $file` "</td></tr>"
done) | sort -n -r +3
cat <<EOF
</table>

<p>Channels the bot is currently in:</p>

<ul>
EOF
sort $CHANNELFILE | xargs -n1 -i echo "<li>" {} "</li>"
cat <<EOF
</ul>

</body>
</html>
EOF
